### ISSUE TITLE
cabal.exe: unrecognised command: v1-install

### ISSUE THREAD

**Issue by Pzixel** [melted/get-idris#11]
```
PS C:\Users\pzixe\Documents\Repos\get-idris> .\get-idris.ps1$
Directory: C:\Users\pzixe\Documents\Repos\get-idris$
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        08.12.2019      1:33                downloads
d-----        08.12.2019      1:33                support
Getting 7-zip
Getting msys64
Getting bootstrap GHC 64-bit
Getting cabal.exe
Starting msys configuration
mkdir: cannot change permissions of '/dev/shm': Permission denied
mkdir: cannot change permissions of '/dev/mqueue': Permission denied
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: Generating pacman keyring master key...
gpg: skipping control `%no-protection' ()
+++++
.+++++
gpg: key ABD7CF67 marked as ultimately trusted
gpg: Done
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
gpg: refreshing 8 keys from hkp://pool.sks-keyservers.net
gpg: requesting key ABD7CF67 from hkp server pool.sks-keyservers.net
gpg: requesting key CA25678A from hkp server pool.sks-keyservers.net
gpg: requesting key AEEA755C from hkp server pool.sks-keyservers.net
gpg: requesting key 3E0D0813 from hkp server pool.sks-keyservers.net
gpg: requesting key 3E652008 from hkp server pool.sks-keyservers.net
gpg: requesting key A47D45A1 from hkp server pool.sks-keyservers.net
gpg: requesting key 2C51581E from hkp server pool.sks-keyservers.net
gpg: requesting key 4CA56930 from hkp server pool.sks-keyservers.net
gpg: key CA25678A: "Alexey Pavlov (Alexpux) <alexey.pawlow@gmail.com>" 4 new signatures
gpg: key AEEA755C: "Martell Malone (martell) <martellmalone@gmail.com>" 3 new signatures
gpg: key 3E0D0813: "Ray Donnelly (MSYS2 Developer - master key) <mingw.android@gmail.com>" 2 new signatures
gpg: key 3E652008: "Ignacio Casal Quinteiro <icquinteiro@gmail.com>" 2 new signatures
gpg: key A47D45A1: "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" 1 new signature
gpg: key 2C51581E: "Martell Malone (MSYS2 Developer) <martellmalone@gmail.com>" not changed
gpg: key 4CA56930: "Ray Donnelly (MSYS2 Developer) <mingw.android@gmail.com>" 2 new signatures
gpg: Total number processed: 7
gpg:              unchanged: 1
gpg:         new signatures: 14
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
gpg: keyserver refresh failed: bad public key
==> ERROR: A specified local key could not be updated from a keyserver.
install-info: warning: no info dir entry in `/usr/share/info/time.info.gz'
Installing packages
warning: gzip-1.8-1 is up to date -- reinstalling
warning: dependency cycle detected:
warning: mingw-w64-x86_64-gcc-libgfortran will be installed before its mingw-w64-x86_64-gcc-libs dependency
Getting and building Idris
Cloning into 'idris'...
remote: Enumerating objects: 92, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (80/80), done.
Receiving objectsremote: Total 67253 (delta 42), reused 26 (delta 12), pack-reused 67161:   % (67253
Receiving objects: 100% (67253/67253), 36.22 MiB | 2.68 MiB/s, done.
Resolving deltas: 100% (45489/45489), done.
Checking out files: 100% (1622/1622), done.
cabal.exe: unrecognised command: v1-install (try --help)
make: *** [Makefile:18: install] Error 1
```

cabal-install version 2.4.1.0

**Comment by melted** [comment]
Thanks for the report!

Looks like the idris update for cabal-install 3.0 broke the script.

**Comment by Pzixel** [comment]
Do I need to update `cabal-install` or anything? I have a haskell installation that actually is working for a while without issues. I installed everything using all defaults in November, so I'm not sure why cabal 2.x is installed. Maybe it's still used with most recent haskel and stack installations.

**Comment by melted** [comment]
I have fixed it by updating the cabal the script downloads, updated msys while I was at it.

**Comment by melted** [comment]
The script uses its own cabal, it was made to function on a machine with nothing installed.

**Comment by Pzixel** [comment]
Unfortunately, still doesn't work to me.

```
cabal.exe: Error: some packages failed to install:
StateVar-1.2-FLi81f6WAjpAfDzv1Vm8MU failed during the final install step. The
exception was:
dieVerbatim: user error (cabal.exe:
'C:\Users\pzixe\Documents\Repos\get-idris\msys\ghc-8.6.3\bin\ghc-pkg.exe'
exited with an error:
StateVar-1.2: Warning: .:3:1: Unknown field: "visibility"
StateVar-1.2: Warning: library-dirs: C:\Program doesn't exist or isn't a
directory
StateVar-1.2: Warning: dynamic-library-dirs: C:\Program doesn't exist or isn't
a directory
StateVar-1.2: Warning: include-dirs: C:\Program doesn't exist or isn't a
directory
StateVar-1.2: Warning: haddock-interfaces:
C:\Users\pzixe\AppData\Roaming\cabal\doc\x86_64-windows-ghc-8.6.3\StateVar-1.2\html\StateVar.haddock
doesn't exist or isn't a file
StateVar-1.2: Warning: haddock-html:
C:\Users\pzixe\AppData\Roaming\cabal\doc\x86_64-windows-ghc-8.6.3\StateVar-1.2\html
doesn't exist or isn't a directory
StateVar-1.2: library-dirs: Files\Haskell is a relative path which makes no
sense (as there is nothing for it to be relative to). You can make paths
relative to the package database itself by using ${pkgroot}. (use --force to
override)
StateVar-1.2: library-dirs: Platform\8.6.5\mingw\lib is a relative path which
makes no sense (as there is nothing for it to be relative to). You can make
paths relative to the package database itself by using ${pkgroot}. (use
--force to override)
StateVar-1.2: dynamic-library-dirs: Files\Haskell is a relative path which
makes no sense (as there is nothing for it to be relative to). You can make
paths relative to the package database itself by using ${pkgroot}. (use
--force to override)
StateVar-1.2: dynamic-library-dirs: Platform\8.6.5\mingw\lib is a relative
path which makes no sense (as there is nothing for it to be relative to). You
can make paths relative to the package database itself by using ${pkgroot}.
(use --force to override)
)
```

[buildlog.txt](https://github.com/melted/get-idris/files/3936599/buildlog.txt)

It looks like something is wrong with Paths, e.g. they are not quoted.

**Comment by melted** [comment]
That is very weird, cabal typically doesn't install stuff in Program Files at all, and nothing like this happens when I run it on a machine without any haskell installation whatsoever, so it's not that I have configured cabal "right".

**Comment by melted** [comment]
I don't think I can help here, because it doesn't seem like those paths originate from the script.

**Comment by Pzixel** [comment]
Thanks for help.

I'm actually confused this is why I used this emoji. You're doing a great job. I think the only option I only have is trying to setup WSL and run idris there. Maybe my environment is trashed but I have no idea what I did wrong to see that error.
